### ISSUE TITLE
Unable to fetch

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/libretro-super#245]
Any idea why this fails?

```
  # if directory exist remove it
  if [[ -d "/home/desktop/retroarch-src" ]]; then
    rm -rf "/home/desktop/retroarch-src"
  fi
  
  # clone and fetch super build (evaluating currently)
  mkdir -p /home/desktop/retroarch-src
  mkdir -p /home/desktop/retroarch-src-git
  cd /home/desktop/retroarch-src-git
  git clone https://github.com/libretro/libretro-super
  cd libretro-super/
  # fetch information
  sh libretro-fetch.sh 
  
  if [ $? == '0' ]; then
    echo -e "\nFetch operation successful...\n"
    sleep 1s
  else
    echo -e "\nFetch operation unsuccessful, aborting..."
    exit
  fi
```

**Comment by ProfessorKaos64** [comment]
Nevermind, this works, the sh prefix for running the script is not ideal.

```
	  mkdir -p /home/desktop/retroarch-src
	  mkdir -p /home/desktop/retroarch-src-git
	  cd /home/desktop/retroarch-src-git
	  git clone https://github.com/libretro/libretro-super
	  cd libretro-super/
	  # fetch information
	  ./libretro-fetch.sh 
	  
	  if [ $? == '0' ]; then
	    echo -e "\nFetch operation successful...\n"
	    sleep 1s
	  else
	    echo -e "\nFetch operation unsuccessful, aborting..."
	    exit
	  fi
```

**Comment by iKarith** [comment]
Correct, libretro-super scripts require bash.  It was easier to make 
the concession of requiring bash >= 2.05a than to require any Bourne 
shell clone and an otherwise fully POSIX build system.

Amusing: Debian and others ship some variant of ash, which is fully 
Bourne-shell compliant because it's smaller and it encourages people 
not to write bashisms into their /bin/sh using scripts.  However 
POSIX-compliance demands several extensions to the Bourne shell that 
ash and dash lack—including those "bashisms" like $() so many purists 
want to get rid of.  *sigh*  At this point the only shells that don't 
have these constructs are the clones and re-implementations of the 
old, limited 1970s era /bin/sh.  *facepalm*

Joseph

**Comment by ProfessorKaos64** [comment]
Interesting informatoin @iKarith (Joe). Thank you for replying, given my goof there. Thank you for the time and effor you and your team put into this repository and project.
