### ISSUE TITLE
Ability to fetch only needed targets?

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/libretro-super#247]
I know for building cores, I can easily use `sed -i -e '/build_libretro_core bsnes/d' libretro-build.sh ` to remove a core, and build globally with `./libretro-build.sh`. With fetch, it does not seem so straigthforward. I did take a look at the [core rules](https://github.com/libretro/libretro-super/blob/master/rules.d/core-rules.sh), which seems to be something of value, but I wanted to know if there was a way to go about this easily, rather than specify multiple lines of  `./libretro-fetch.sh $target`

I was unsure if this was as simple as commenting out a line such as 
`register_core "meteor" -ngc -ps3 -psp1 -qnx -wii`

**Comment by ProfessorKaos64** [comment]
Maybe nevermind, I think this works:
`sed -i -e 's|register_core "bsnes"|#register_core "bsnes"|g' "$git_dir/rules.d/core-rules.sh" `

**Comment by iKarith** [comment]
You can actually also just specify a core or cores to fetch or build.  
The ability to disable or enable individual cores will be part of the 
libretro-super.sh script which will ultimately replace 
libretro-build.sh and libretro-fetch.sh both.  Probably other scripts 
as well.

If you want to have a look at it, an incomplete version is available 
in https://github.com/iKarith/libretro-super.git and the main script 
at least is pretty well documented.  I think you'll appreciate little 
things like how it can produce individual core build logs (in case 
something doesn't build and you want to figure out why) and how it 
only builds cores that have changed.

It needs a little polish, I have a few changes to push to it still, 
and what I'm trying to do to replace $platform isn't going to work 
(and doing something about it is going to have to wait for me to 
write the configuration module which will behave rather like the 
VMware Tools installation script or the Linux kernel's menuconfig, 
depending on what you've got installed on your system.

Feedback wanted, because libretro-super.sh is probably about a week 
or so from becoming the new build script for libretro-super, if I can 
actually get some time to finish it.

Joseph

**Comment by ProfessorKaos64** [comment]
Nice, I'll def. take a look, since this will affect my [build script](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/testing/scriptmodules/emu-from-source.shinc) for building cores for SteamOS and trying to get emulation worked into my test SteamOS machine. I'll try to test this out this weekend, friday at the earliers.
