### ISSUE TITLE
[Travis] Linux Builds don't run

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-super#578]
@bparker06 If you look at any Linux Travis build, you will see it doesn't run:
https://travis-ci.org/libretro/parallel-n64/builds/296058221

```
buildbot job started at: Thu Nov  2 02:14:55 UTC 2017
buildbot job: recipes/linux/cores-linux-x64-generic processing parallel_n64
--------------------------------------------------
Variables:
URL https://github.com/libretro/parallel-n64.git
REPO TYPE PROJECT
ENABLED YES
COMMAND GENERIC_GL
MAKEFILE Makefile
DIR libretro-parallel_n64
SUBDIR .
pulling changes from repo https://github.com/libretro/parallel-n64.git... 
Already up-to-date.
buildbot job: building parallel_n64 up-to-date
buildbot job finished at: Thu Nov  2 02:14:56 UTC 2017
buildbot job: recipes/linux/cores-linux-x64-generic Building Retroarch-unix
--------------------------------------------------
WORKINGDIR=/home/travis/libretro-super
RELEASE=NO
FORCE=NO
RADIR=
./libretro-buildbot-recipe.sh: line 1133: recipes/linux/cores-linux-x64-generic.ra: No such file or directory
The command "./build.sh" exited with 0.
```

It attempts to build RetroArch, rather than the core itself. It fails to find `recipes/linux/cores-linux-x64-generic.ra`.

**Comment by bparker06** [comment]
The `.ra` thing is unrelated, it always did that. But the reason it doesn't build the core now is because it's using the existing pre-cloned folder (to be able to support PRs), which is already "up-to-date" when the buildbot recipe script runs, so it skips it. I pushed a fix to force it to always build, so it should be working now. Also just pushed a commit to parallel so you can keep an eye on it there.

**Comment by bparker06** [comment]
Hmm, it's definitely building the core now, but also trying to build RA, when it didn't used to do that. Will look into that some more but for now at least the core builds are working.

**Comment by RobLoach** [comment]
Nice one! Thanks a lot.
